![Algoritmos e Estrutura de Dados II - Prof Piva](AED2_banner.jpg)

## Aula 6 - Pilhas

### Primeira Implementação

In [17]:
# Implementacao da classe Pilha
class Stack:
    # Inicia com uma pilha vazia
    def __init__(self):
        self.itens = []
    
    # Verifica se pilha esta vazia
    def is_empty(self):
        return self.itens == []
    
    # Adiciona elemento no topo (topo e o final da lista)
    def push(self, item):
        self.itens.append(item)
        print(f"PUSH {item}")

    # Remove elemento do topo (final da lista)
    def pop(self):
        print("POP")
        return self.itens.pop()
    
    # Obtem o elemento do topo (mas nao remove)
    def peek(self):
    # Em Python, indice -1 retorna ultimo elemento (topo)
        return self.itens[-1]
    
    # Retorna o numero de elementos da pilha
    def size(self):
        return len(self.itens)
    
    # Imprime pilha na tela
    def print_stack(self):
        print(self.itens)

In [19]:
# TESTANDO
S = Stack()

In [41]:
S.print_stack()

[1]


In [27]:
S.push(1)

PUSH 1


In [29]:
S.push(2)

PUSH 2


In [31]:
S.push(3)

PUSH 3


In [33]:
S.print_stack()

[1, 2, 3]


In [35]:
S.pop()

POP


3

In [37]:
S.pop()

POP


2

In [39]:
S.print_stack()

[1]


In [43]:
S.push(7)

PUSH 7


In [45]:
S.push(8)

PUSH 8


In [47]:
S.push(9)

PUSH 9


In [49]:
S.print_stack()

[1, 7, 8, 9]


In [51]:
print(S.is_empty())

False


### Segunda Implementação

In [65]:
import numpy as np

In [67]:
class Pilha:
    def __init__(self, capacidade):
        self.__capacidade = capacidade
        self.__topo = -1
        self.__valores = np.zeros(self.__capacidade, dtype=int)

    def __pilha_cheia(self):
        if self.__topo == self.__capacidade - 1:
            return True
        else:
            return False
    
    def __pilha_vazia(self):
        if self.__topo == -1:
            return True
        else:
            return False
    
    def empilhar(self, valor):
        if self.__pilha_cheia():
            print('A pilha está cheia')
        else:
            self.__topo += 1
            self.__valores[self.__topo] = valor
            # return -1
    
    def desempilhar(self):
        if self.__pilha_vazia():
            print('A pilha está vazia')
        else:
            # aux = self.__valores[self.__topo]
            self.__valores[self.__topo] = 0
            self.__topo -= 1
            # return aux
    
    def ver_topo(self):
        if self.__topo != -1:
            return self.__valores[self.__topo]
        else:
            return -1
    
    # Imprime pilha na tela
    def imprime_pilha(self):
        print(self.__valores)

In [71]:
pilha = Pilha(5)

In [73]:
pilha.imprime_pilha()

[0 0 0 0 0]


In [75]:
pilha.ver_topo()

-1

In [77]:
pilha.empilhar(1)
pilha.ver_topo()

1

In [79]:
pilha.empilhar(1)
pilha.empilhar(2)
pilha.empilhar(3)
pilha.empilhar(4)

In [81]:
pilha.imprime_pilha()

[1 1 2 3 4]


In [83]:
pilha.empilhar(6)

A pilha está cheia


In [85]:
pilha.ver_topo()

4

In [87]:
pilha.desempilhar()

In [89]:
pilha.ver_topo()

3

In [91]:
pilha.desempilhar()
pilha.desempilhar()
pilha.desempilhar()

In [93]:
pilha.ver_topo()

1

In [95]:
pilha.imprime_pilha()

[1 0 0 0 0]


In [97]:
pilha.desempilhar()

In [99]:
pilha.imprime_pilha()

[0 0 0 0 0]


In [101]:
pilha.desempilhar()

A pilha está vazia


# Vamos à Prática!
## Exercício

Utilização de pilhas para conversão de números inteiros em decimal para binário (método da divisão sucessiva por 2).

**Utilização do classe Stack..**

In [103]:
# Função que converte um número decimal para binário
def decimal_binario(numero):
 s = Stack()
 while numero > 0:
     resto = numero % 2
     s.push(resto)
     numero = numero // 2
 binario = ''
 while not s.is_empty():
     binario = binario + str(s.pop())
 return binario

### Testando!
233 --> binário

In [105]:
# TESTANDO
n = int(input('Entre com um número inteiro: '))
print(f"O valor {n} em binário é: {decimal_binario(n)}") 

Entre com um número inteiro:  44


PUSH 0
PUSH 0
PUSH 1
PUSH 1
PUSH 0
PUSH 1
POP
POP
POP
POP
POP
POP
O valor 44 em binário é: 101100


In [107]:
class EditorTexto:
    def __init__(self):
        self.texto = ""  # Texto atual
        self.historico = []  # Pilha de ações realizadas
        self.refazer_historico = []  # Pilha de ações desfeitas
    
    def adicionar_texto(self, novo_texto):
        self.historico.append(self.texto)  # Salva o estado atual no histórico
        self.refazer_historico.clear()  # Limpa o histórico de redo ao adicionar novo texto
        self.texto += novo_texto  # Adiciona o novo texto

    def undo(self):
        if self.historico:  # Verifica se há ações no histórico
            self.refazer_historico.append(self.texto)  # Armazena o estado atual no histórico de redo
            self.texto = self.historico.pop()  # Retorna ao estado anterior
        else:
            print("Nada para desfazer.")
    
    def redo(self):
        if self.refazer_historico:  # Verifica se há ações para refazer
            self.historico.append(self.texto)  # Armazena o estado atual no histórico de undo
            self.texto = self.refazer_historico.pop()  # Refaz a última ação desfeita
        else:
            print("Nada para refazer.")
    
    def mostrar_texto(self):
        return self.texto

# Exemplo de uso
editor = EditorTexto()

# Adicionando texto
editor.adicionar_texto("Hello")
print(editor.mostrar_texto())  # Saída: "Hello"

editor.adicionar_texto(" World")
print(editor.mostrar_texto())  # Saída: "Hello World"

# Desfazendo
editor.undo()
print(editor.mostrar_texto())  # Saída: "Hello"

# Refazendo
editor.redo()
print(editor.mostrar_texto())  # Saída: "Hello World"

Hello
Hello World
Hello
Hello World


### Fim Teoria Aula 6